Fix initial disbursement logic
teamsempo/SempoBlockchain pull request #487
Opened 2020-10-06 21:00 UTC by michielderoos

**Describe the Pull Request**

A clear and concise description of the features implemented in the PR of bugs fixed.

**Todo**

- [ ] Link relevant [trello card](https://trello.com/b/PA2LhlOh/sempo-dev) or [related issue](https://github.com/teamsempo/SempoBlockchain/issues) to the pull request
- [ ] Request review from relevant @person or team
- [ ] QA your pull request. This includes running the app, login, testing changes etc.
- [ ] Bump [backend](https://github.com/teamsempo/SempoBlockchain/blob/e3eb0f480e86d5a8ef2c1814127b70ff018671c4/config.py#L7) and/or [frontend](https://github.com/teamsempo/SempoBlockchain/blob/e3eb0f480e86d5a8ef2c1814127b70ff018671c4/app/package.json#L3) versions following Semver

2020-10-06 21:59 UTC, michielderoos commented
![](https://github.trello.services/images/mini-trello-icon.png) [Review Approve and Disburse](https://trello.com/c/u5pvqAUn/539-review-approve-and-disburse)

2020-10-07 10:19 UTC, enjeyw requested changes
Just something I'm not quite sure about in the top level of the API

2020-10-07 10:19 UTC, enjeyw commented on app/server/api/transfer_account_api.py
> +                transfer_account.approve_initial_disbursement()
I think this is unreachable due to:
```
     if approve: 
                transfer_account.is_approved = True
```

Shouldn't they together be:

```
if not transfer_account.is_approved and approve:
                transfer_account.is_approved = True
                transfer_account.approve_initial_disbursement()
```

2020-10-07 10:19 UTC, enjeyw commented on app/server/api/transfer_account_api.py
> +                    transfer_account.approve_initial_disbursement()
same here

2020-10-08 09:47 UTC, enjeyw approved these changes
Looks good!

2020-10-08 10:16 UTC, merged