Add unstarted status
teamsempo/SempoBlockchain pull request #503
Opened 2020-10-20 18:55 UTC by michielderoos

**Describe the Pull Request**

Makes `blockchain_status`  be `UNSTARTED` when a transfer is `resolve_as_rejected`'d

**Todo**

- [ ] Link relevant [trello card](https://trello.com/b/PA2LhlOh/sempo-dev) or [related issue](https://github.com/teamsempo/SempoBlockchain/issues) to the pull request
- [ ] Request review from relevant @person or team
- [ ] QA your pull request. This includes running the app, login, testing changes etc.
- [ ] Bump [backend](https://github.com/teamsempo/SempoBlockchain/blob/e3eb0f480e86d5a8ef2c1814127b70ff018671c4/config.py#L7) and/or [frontend](https://github.com/teamsempo/SempoBlockchain/blob/e3eb0f480e86d5a8ef2c1814127b70ff018671c4/app/package.json#L3) versions following Semver

2020-10-20 18:56 UTC, michielderoos commented
![](https://github.trello.services/images/mini-trello-icon.png) [Blockchain status rejected/unstarted if approval is rejected](https://trello.com/c/aC2xw4Ab/647-blockchain-status-rejected-unstarted-if-approval-is-rejected)

2020-10-21 23:22 UTC, tristanhcole commented on app/migrations/versions/bb92df9cb6e3_.py
> +    op.execute("ALTER TYPE blockchainstatus ADD VALUE 'UNSTARTED'")
I think we should probably also convert the previous Credit Transfer's `blockchain_status=UNSTARTED` whom have `transfer_status=REJECTED`

2020-10-26 04:25 UTC, tristanhcole commented on app/migrations/seed.py
> +    db.session.commit()
@michielderoos can we please have this as a raw SQL operation directly in the `bb92df9cb6e3_.py` migration. This means the data is changed only once when DB is migrated and in a sequential order that is expected. As `seed.py` is run basically every time the app is spun up or updated

2020-10-26 04:25 UTC, tristanhcole requested changes
See https://github.com/teamsempo/SempoBlockchain/pull/503/files#r511713520

2020-10-26 04:26 UTC, tristanhcole commented on app/migrations/seed.py
> +    db.session.commit()
I also spoke to @enjeyw about this and he concurs

2020-10-26 16:28 UTC, michielderoos commented
> See https://github.com/teamsempo/SempoBlockchain/pull/503/files#r511713520

@tristanhcole Makes sense, Done!

2020-10-27 09:09 UTC, tristanhcole approved these changes
Tested and works well for me!

2020-10-27 15:09 UTC, merged