Fix export api
teamsempo/SempoBlockchain pull request #521
Opened 2020-10-27 17:26 UTC by michielderoos

**Describe the Pull Request**

Would load forever trying to get `g.user.transfer_account`, I think this logic was created before a user could have multiple transfer accounts. Changed to make it get the primary transfer account!

**Todo**

- [ ] Link relevant [trello card](https://trello.com/b/PA2LhlOh/sempo-dev) or [related issue](https://github.com/teamsempo/SempoBlockchain/issues) to the pull request
- [ ] Request review from relevant @person or team
- [ ] QA your pull request. This includes running the app, login, testing changes etc.
- [ ] Bump [backend](https://github.com/teamsempo/SempoBlockchain/blob/e3eb0f480e86d5a8ef2c1814127b70ff018671c4/config.py#L7) and/or [frontend](https://github.com/teamsempo/SempoBlockchain/blob/e3eb0f480e86d5a8ef2c1814127b70ff018671c4/app/package.json#L3) versions following Semver

2020-10-28 21:16 UTC, tristanhcole commented
![](https://github.trello.services/images/mini-trello-icon.png) [Change me_export_api to use right transfer account](https://trello.com/c/J6q6hWfr/660-change-meexportapi-to-use-right-transfer-account)

2020-10-29 03:58 UTC, tristanhcole approved these changes
LGTM!

2020-10-29 10:04 UTC, enjeyw requested changes
```
            for index, credit_transfer in enumerate(credit_transfer_list):
```
Just loading this line (not even the loop) still takes fooorrreeevvvveerrrr on my computer if i load in lots of data! I think it's what's timing out on the server.

Setting ```.enable_eagerloads(False)``` on the previous lines makes things better, but I haven't checked if there's any further optimisations by loading in transfer usages....

2020-10-29 13:34 UTC, michielderoos commented
> ```
>             for index, credit_transfer in enumerate(credit_transfer_list):
> ```
> 
> Just loading this line (not even the loop) still takes fooorrreeevvvveerrrr on my computer if i load in lots of data! I think it's what's timing out on the server.
> 
> Setting `.enable_eagerloads(False)` on the previous lines makes things better, but I haven't checked if there's any further optimisations by loading in transfer usages....

@enjeyw I found it about 3x faster with `.enable_eagerloads(True)` rather than ` .enable_eagerloads(False)`. One thing which I think will make it way faster though, is #525  since it adds indexes on `recipient_transfer_account_id` and `sender_transfer_account_id`

2020-10-30 09:03 UTC, enjeyw commented on app/server/api/export_api.py
> +                'file_url': 'a',
doi

2020-10-30 10:31 UTC, enjeyw reviewed
That line is still craaazzzy slow for me if i use a large dataset... i think it's cos credit_transfers joins on transfer accounts and a bunch of other things we don't use?

2020-11-05 10:04 UTC, enjeyw approved these changes
LGTM!

2020-11-05 13:31 UTC, merged