Paginate transfer account search
teamsempo/SempoBlockchain pull request #649
Opened 2021-03-19 05:06 UTC by enjeyw

**Describe the Pull Request**

Adds pagination to the transfer account query/table
**Todo**

- [ ] Link relevant [trello card](https://trello.com/b/PA2LhlOh/sempo-dev) or [related issue](https://github.com/teamsempo/SempoBlockchain/issues) to the pull request
- [ ] Request review from relevant @person or team
- [ ] QA your pull request. This includes running the app, login, testing changes, checking [accessibility](https://www.a11yproject.com/checklist/) etc.
- [ ] Bump [backend](https://github.com/teamsempo/SempoBlockchain/blob/e3eb0f480e86d5a8ef2c1814127b70ff018671c4/config.py#L7) and/or [frontend](https://github.com/teamsempo/SempoBlockchain/blob/e3eb0f480e86d5a8ef2c1814127b70ff018671c4/app/package.json#L3) versions following Semver
- [ ] Add release notes to [unreleased changelog](https://github.com/teamsempo/SempoBlockchain/blob/master/CHANGELOG.md#unreleased)

2021-03-19 14:03 UTC, michielderoos requested changes
This is a bit broken for me-- when I click back and forth between pages it hangs and I get a Page Unresponsive error 
![image](https://user-images.githubusercontent.com/2199643/111792188-c704eb80-88a2-11eb-8001-4aaf37447027.png)

2021-03-25 06:30 UTC, tristanhcole approved these changes
Made two small changes. Otherwise, code looks solid to me! Nice @enjeyw. Tested with 300 users.

@michielderoos if you can test on a larger user set to make sure the page doesn't time out that would be awesome!

2021-03-25 06:30 UTC, tristanhcole commented on app/client/components/filterModule/queryConstructor.tsx
>    };
I added a small timeout so that it only searches once the user stops typing. Personally, I find this to be a better UX

2021-03-25 06:30 UTC, tristanhcole commented on app/client/components/filterModule/queryConstructor.tsx
> +  timeout: any;
couldn't work out typing, so just left as `any`

¯\_(ツ)_/¯

2021-03-25 06:30 UTC, tristanhcole commented on app/client/components/pages/transferAccountListPage.jsx
> -          <QueryConstructor filterObject="user" />
This was causing a double load _without_ pagination on the first load

2021-03-25 06:30 UTC, tristanhcole commented on app/client/components/transferAccount/StandardTransferAccountList.tsx
>    }
Whenever there is a new query, we reset to page 1
https://ux.stackexchange.com/questions/129073/should-the-pagination-be-reset-when-changing-the-order

2021-03-25 06:30 UTC, tristanhcole commented on app/client/components/transferAccount/StandardTransferAccountList.tsx
> +            currentPage: this.state.page,
on initial page load, the current pagination page option wasn't being selected. adding `currentPage` fixes this

2021-03-25 06:30 UTC, tristanhcole commented on app/client/components/filterModule/queryConstructor.tsx
>    };
We can remove this if you don't agree @michielderoos, I'm not strongly opinionated

2021-03-25 14:16 UTC, michielderoos approved these changes
Awesome! Works perfect!

2021-03-25 14:17 UTC, merged