fix: project settings fields
teamsempo/SempoBlockchain pull request #662
Opened 2021-03-31 21:55 UTC by tristanhcole

**Describe the Pull Request**
Fix project setting field.

**Todo**

- [ ] Link relevant [trello card](https://trello.com/b/PA2LhlOh/sempo-dev) or [related issue](https://github.com/teamsempo/SempoBlockchain/issues) to the pull request
- [ ] Request review from relevant @person or team
- [ ] QA your pull request. This includes running the app, login, testing changes, checking [accessibility](https://www.a11yproject.com/checklist/) etc.
- [ ] Bump [backend](https://github.com/teamsempo/SempoBlockchain/blob/e3eb0f480e86d5a8ef2c1814127b70ff018671c4/config.py#L7) and/or [frontend](https://github.com/teamsempo/SempoBlockchain/blob/e3eb0f480e86d5a8ef2c1814127b70ff018671c4/app/package.json#L3) versions following Semver
- [ ] Add release notes to [unreleased changelog](https://github.com/teamsempo/SempoBlockchain/blob/master/CHANGELOG.md#unreleased)

2021-03-31 21:59 UTC, tristanhcole commented
![](https://github.trello.services/images/mini-trello-icon.png) [Project Settings Timezone Error](https://trello.com/c/I5yQcTa9/784-project-settings-timezone-error)

2021-03-31 21:59 UTC, tristanhcole commented
![](https://github.trello.services/images/mini-trello-icon.png) [Project Settings Timezone Error](https://trello.com/c/I5yQcTa9/784-project-settings-timezone-error)

2021-04-01 16:20 UTC, michielderoos requested changes
Just one little note, otherwise looks good!

2021-04-01 16:20 UTC, michielderoos commented on app/migrations/versions/3b14e2aff4ea_.py
> +    op.alter_column('organisation', '_timezone',
This migration fails on existing databases where there are existing `null` timezones   
![image](https://user-images.githubusercontent.com/2199643/113324027-009b1500-92ed-11eb-835d-db449c0f50e8.png)

2021-04-14 19:56 UTC, michielderoos approved these changes
Had to fix the tests, but LGTM!

2021-04-15 04:23 UTC, merged