[WIP] Fix transfer account list checkmark pagination
teamsempo/SempoBlockchain pull request #668
Opened 2021-04-12 22:53 UTC by michielderoos

**Describe the Pull Request**

Accounts checked when you change pages are remembered!  
One bug remains-- when you select all on page one, then click to page two, then to page three, page two doesn't become selected until you change pages.

**Todo**

- [ ] Link relevant [trello card](https://trello.com/b/PA2LhlOh/sempo-dev) or [related issue](https://github.com/teamsempo/SempoBlockchain/issues) to the pull request
- [ ] Request review from relevant @person or team
- [ ] QA your pull request. This includes running the app, login, testing changes, checking [accessibility](https://www.a11yproject.com/checklist/) etc.
- [ ] Bump [backend](https://github.com/teamsempo/SempoBlockchain/blob/e3eb0f480e86d5a8ef2c1814127b70ff018671c4/config.py#L7) and/or [frontend](https://github.com/teamsempo/SempoBlockchain/blob/e3eb0f480e86d5a8ef2c1814127b70ff018671c4/app/package.json#L3) versions following Semver
- [ ] Add release notes to [unreleased changelog](https://github.com/teamsempo/SempoBlockchain/blob/master/CHANGELOG.md#unreleased)

2021-04-12 22:54 UTC, michielderoos commented on app/client/components/transferAccount/TransferAccountList.tsx
> -    if (prevProps.providedSelectedRowKeys != this.props.providedSelectedRowKeys) {
I think this was all made irrelevant by `preserveSelectedRowKeys`!

2021-04-14 08:26 UTC, tristanhcole commented on app/client/components/transferAccount/TransferAccountList.tsx
> +    const numberSelected = this.props.paginationOptions?.items ? allSelected ? this.props.paginationOptions?.items - unselectedRowKeys.length : selectedRowKeys.length : selectedRowKeys.length
Changed from "All" to a number. This fixes the bug that shows "All Selected" when you select all and then _unselect_ a user.

2021-04-14 08:27 UTC, tristanhcole approved these changes
Fixed the remaining bug. Tested and code looks good to me

2021-04-14 08:47 UTC, tristanhcole requested changes
Hmmmm still needs a bit of work - when I select all and then unselect, and got to another page, it breaks. Will investigate.

2021-04-15 04:22 UTC, tristanhcole approved these changes
This now works on the primary `/accounts` page. We still need to do some work to get the view all recipients page working

2021-04-15 12:57 UTC, merged