feat: implement rate limiting on auth API's
teamsempo/SempoBlockchain pull request #703
Opened 2021-05-21 03:37 UTC by tristanhcole

**Describe the Pull Request**
Rate limiting was already installed, so just uncommented. Implements rate limiting on Auth API's. @michielderoos could you test this with docker? We might need to look at this https://flask-limiter.readthedocs.io/en/stable/#deploying-an-application-behind-a-proxy

**Todo**

- [ ] Link relevant [trello card](https://trello.com/b/PA2LhlOh/sempo-dev) or [related issue](https://github.com/teamsempo/SempoBlockchain/issues) to the pull request
- [ ] Request review from relevant @person or team
- [ ] QA your pull request. This includes running the app, login, testing changes, checking [accessibility](https://www.a11yproject.com/checklist/) etc.
- [ ] Bump [backend](https://github.com/teamsempo/SempoBlockchain/blob/e3eb0f480e86d5a8ef2c1814127b70ff018671c4/config.py#L7) and/or [frontend](https://github.com/teamsempo/SempoBlockchain/blob/e3eb0f480e86d5a8ef2c1814127b70ff018671c4/app/package.json#L3) versions following Semver
- [ ] Add release notes to [unreleased changelog](https://github.com/teamsempo/SempoBlockchain/blob/master/CHANGELOG.md#unreleased)

2021-05-21 03:37 UTC, tristanhcole commented on app/server/__init__.py
> +limiter = Limiter(key_func=get_remote_address)
@michielderoos do we want defaults across the app?

2021-05-21 03:38 UTC, tristanhcole commented on app/server/api/auth_api.py
> +    decorators = [limiter.limit("1/second")]
This seemed reasonable? Maybe something stricter?

2021-05-21 03:41 UTC, tristanhcole commented
![](https://github.trello.services/images/mini-trello-icon.png) [[Medium - 5.3] Username and Phone Number Enumeration](https://trello.com/c/1UinBkXq/836-medium-53-username-and-phone-number-enumeration)

2021-06-02 17:14 UTC, michielderoos requested changes
I couldn't get this working locally, so I manually implemented some rate limiting logic in #710

2021-06-03 06:29 UTC, tristanhcole commented
Closing in favour of #710

2021-06-03 06:29 UTC, closed without merging