refactor: user page
teamsempo/SempoBlockchain pull request #725
Opened 2021-06-30 03:15 UTC by tristanhcole

**Describe the Pull Request**
Refactor user page to ant design.
<img width="1785" alt="Screen Shot 2021-06-29 at 3 11 32 pm" src="https://user-images.githubusercontent.com/27039316/123896610-0adab700-d9a1-11eb-82ea-b0cda27508fc.png">

**Todo**

- [ ] Link relevant [trello card](https://trello.com/b/PA2LhlOh/sempo-dev) or [related issue](https://github.com/teamsempo/SempoBlockchain/issues) to the pull request
- [ ] Request review from relevant @person or team
- [ ] QA your pull request. This includes running the app, login, testing changes, checking [accessibility](https://www.a11yproject.com/checklist/) etc.
- [ ] Bump [backend](https://github.com/teamsempo/SempoBlockchain/blob/e3eb0f480e86d5a8ef2c1814127b70ff018671c4/config.py#L7) and/or [frontend](https://github.com/teamsempo/SempoBlockchain/blob/e3eb0f480e86d5a8ef2c1814127b70ff018671c4/app/package.json#L3) versions following Semver
- [ ] Add release notes to [unreleased changelog](https://github.com/teamsempo/SempoBlockchain/blob/master/CHANGELOG.md#unreleased)

2021-06-30 03:21 UTC, tristanhcole commented
![](https://github.trello.services/images/mini-trello-icon.png) [Refactor user page](https://trello.com/c/cPn4gAYk/858-refactor-user-page)

2021-06-30 03:22 UTC, tristanhcole commented on app/server/utils/user.py
> +
Right now, if you try to update a users phone to an existing user phone, it will just silently fail

2021-06-30 03:23 UTC, tristanhcole commented on app/server/models/transfer_usage.py
> +            db.session.flush()
If we don't flush here, then we won't have an ID to tie the new transfer usage to the user

2021-07-02 19:20 UTC, michielderoos requested changes
I found a bug where if you enter a phone number outside of the org's country code, it will prepend a country code to the phone number incorrectly. Example (on a Vanuatu test instance):  
Step 1:  
Enter valid out-of-region phone number  
![image](https://user-images.githubusercontent.com/2199643/124319593-d4dc3500-db50-11eb-9a6c-564b03e03d5c.png)
   
Step 2:  
Save  
  
Step 3:  
![image](https://user-images.githubusercontent.com/2199643/124319630-e1608d80-db50-11eb-86ce-21df9f220e7f.png)
The number entered in step 1 had a new country code (678) prepended, even though it was a valid US number.

2021-07-12 00:50 UTC, tristanhcole commented on app/client/components/user/SingleUserManagement.tsx
> +        phone: "+" + form.phone,
Fixes phone number bug

2021-07-12 00:51 UTC, tristanhcole commented
> I found a bug where if you enter a phone number outside of the org's country code, it will prepend a country code to the phone number incorrectly. Example (on a Vanuatu test instance):
> Step 1:
> Enter valid out-of-region phone number
> ![image](https://user-images.githubusercontent.com/2199643/124319593-d4dc3500-db50-11eb-9a6c-564b03e03d5c.png)
> 
> Step 2:
> Save
> 
> Step 3:
> ![image](https://user-images.githubusercontent.com/2199643/124319630-e1608d80-db50-11eb-86ce-21df9f220e7f.png)
> The number entered in step 1 had a new country code (678) prepended, even though it was a valid US number.

Fixed: https://github.com/teamsempo/SempoBlockchain/pull/725#discussion_r667563085

2021-07-12 16:06 UTC, michielderoos approved these changes
Tested, Looks good!

2021-07-13 00:40 UTC, merged